### ISSUE TITLE
The start / stop button no longer works en core version 2023.12.3

### ISSUE THREAD

**Issue by Topbullot** [Vost3/hass-palazzetti#16]
Hi,
since i've upgraded my HASS server in core version 2023.12.3 the switch stove no longer works.
For example when the stove is yet started and you want to stop it, when you push it to stop the stove the button move well and change in grey color for 1 second and go back to the initial position without doing anything.
I don't have any error in log file with debug mode available.
As i use a Hassio version of Home assistant i'm not able to use tcpdump to check the dialog between the server and the stove.
When i use the service tab to test the service "palazzetti.set_parms" all works fine i can stop and start the stove. The problem is only when i use the switch trough the lovelace dashboard.

Restoring the core version 2023.11.3 fixe the problem.

Thanks if you can investigate on this problem.

**Comment by djpostka** [comment]
Hi, same problem here.

**Comment by pouletmou** [comment]
Hello,
I'm facing the same issue, I rollbacked on 2023.11 for now.
Have a nice day.

**Comment by vetranolorenzo** [comment]
Same problem for me too, has anyone found a solution?

**Comment by jere19** [comment]
Beside rolling back to 2023.11, i haven't found a solution either...
I spent a day trying to troubleshoot the issue, but couldn't even get error messages in the logs.

Could this be liked to the services now being able to have return values?

**Comment by Vost3** [comment]
Issue report on Hass-core [https://github.com/home-assistant/core/issues/106655](here)

**Comment by pouletmou** [comment]
> Issue report on Hass-core [https://github.com/home-assistant/core/issues/106655](here)

thanks a lot Vost3 ;)

**Comment by Topbullot** [comment]
OK thank you for your investigation.

**Comment by Vost3** [comment]
Hello there
Bug fix released. 
The value sent by "switch template" has change since release 2023.11.4

Waiting your feedbacks for close this issue ;)

++

**Comment by djpostka** [comment]
> Hello there Bug fix released. The value sent by "switch template" has change since release 2023.11.4
> 
> Waiting your feedbacks for close this issue ;)
> 
> ++

Hi,

I modified the updated files (manifest.json and __init__.py), updated hass to 2023.12.4 but it still doesn't work.

**Comment by pouletmou** [comment]
Hello, 
I'm on 2023.12.4 with Ines 9KW and everything is fine now after your fix ;)

**Comment by Vost3** [comment]
Strange, that work now here in prod env.
The only change is in the "set_status" method in file "__init__.py"
Have you restart your install ?
Have you this in the method "set_status"

![image](https://github.com/Vost3/hass-palazzetti/assets/24756166/e10a2d08-8d17-48df-aed0-75115793f09f)

**Comment by Vost3** [comment]
> Hello, I'm on 2023.12.4 with Ines 9KW and everything is fine now after your fix ;)

Thank for your feedback 
Bonne fête de fin d'année @ toi @pouletmou

**Comment by djpostka** [comment]
Je pense que tu est français, ça sera donc plus simple en français. Oui j'ai bien les même ligne et j'ai bien reboot entièrement mon hass.

**Comment by pouletmou** [comment]
> > Hello, I'm on 2023.12.4 with Ines 9KW and everything is fine now after your fix ;)
> 
> Thank for your feedback Bonne fête de fin d'année @ toi @pouletmou

Bonnes fêtes également !

**Comment by djpostka** [comment]
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.palazzetti
Source: custom_components/palazzetti/__init__.py:229
Integration: Palazzetti Stove (documentation)
First occurred: 14:50:55 (8 occurrences)
Last logged: 15:01:02

Error returned by CBox - retry in 2 seconds (CMD)
```

J'ai cette erreur, et ma cbox (non officiel) est bien joignable, a son ip en http, pas en https.

**Comment by Topbullot** [comment]
Hi every body,
Files modified, upgraded core in version 2023.12.4 and the button works fine again.
Thanks to every body and Vost3 for fixing this problem.

**Comment by djpostka** [comment]
ok, it's ok fort me, thanks

**Comment by Vost3** [comment]
> ok, it's ok fort me, thanks

@djpostka : Perfect. What was the problem ( [mail me](mailto:tivw@pm.me) if you prefere for french speaking )
@Topbullot : Perfect. Thank for your feedback

**Comment by djpostka** [comment]
i have a palacontrol from [Domochip](https://github.com/Domochip) (it's a clone of CBOX). The CMD+OFF or CMD+ON is captital letters only, i just edit the init.py with capitals letters. Thank you for your job, it's realy useful.

**Comment by vetranolorenzo** [comment]
Solved, everything works normally, thanks for the work done.
